//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public int AppId { get; set; }
        public System.Guid AppKey { get; set; }
        public byte KeyFor { get; set; }
        public byte Status { get; set; }
    }
}
