//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRenewal
    {
        public int ClientRenewalId { get; set; }
        public int ClientId { get; set; }
        public int ProjectTypeId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public decimal RenewalAmount { get; set; }
        public byte RenewalStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
