//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string ShortName { get; set; }
        public string CompanyAddress { get; set; }
        public string CityName { get; set; }
        public string DistrictName { get; set; }
        public string StateName { get; set; }
        public string PinCode { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string AlternateNo { get; set; }
        public string Website { get; set; }
        public string LogoPNG { get; set; }
        public string Logo { get; set; }
        public byte Status { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual StaffLogin StaffLogin { get; set; }
    }
}
