//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseId { get; set; }
        public int ExpenseHeadId { get; set; }
        public string Description { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public byte PaymentMode { get; set; }
        public decimal Amount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ExpenseHead ExpenseHead { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
