//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int LoginLogId { get; set; }
        public string UserName { get; set; }
        public string LoginPassword { get; set; }
        public string ClientBrowser { get; set; }
        public string LoginDevice { get; set; }
        public string IPAddress { get; set; }
        public string ReferrerUrl { get; set; }
        public byte LoginResult { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<byte> UserType { get; set; }
        public string GoogleLocation { get; set; }
        public string IMEINo { get; set; }
    }
}
