//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Backups = new HashSet<Backup>();
            this.Databases = new HashSet<Database>();
            this.Databases1 = new HashSet<Database>();
            this.StaffLogins = new HashSet<StaffLogin>();
        }
    
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public string StaffCode { get; set; }
        public int DesignationId { get; set; }
        public byte StaffType { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
        public string AlternateNo { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string StaffPhoto { get; set; }
        public string Qualification { get; set; }
        public string FullAddress { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int DepartmentId { get; set; }
        public byte Status { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Backup> Backups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Database> Databases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Database> Databases1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffLogin> StaffLogins { get; set; }
    }
}
